version: '3.8'
services:
  web_server:
    image: nginx:latest
    volumes:
      - documentation_sphinx_deploy:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    
  cron_builder:
    build:
      context: ./cron_srv/
      dockerfile: dockerfile
    volumes:
      - documentation_sphinx_build:/documentation_sphinx_build
      - documentation_sphinx_deploy:/documentation_sphinx_deploy
      - ./repo_list:/repo_list
volumes:
  documentation_sphinx_build:
  documentation_sphinx_deploy:
