# Dockerfile.cron
FROM sphinxdoc/sphinx:7.4.6

RUN apt update && apt install -y --no-install-recommends \
    bash \
    busybox \
    cron \
    git \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip3 install pyyaml sphinx_rtd_theme

# COPY crontab /tmp/crontab
COPY build_doc.py /build_doc.py
COPY entrypoint.sh /entrypoint.sh
# RUN crontab /tmp/crontab


RUN chmod +x /build_doc.py /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]